### ISSUE TITLE
[SET] 프로젝트 관련 기본 세팅

### ISSUE THREAD

**Issue by devEdok13** [codestates-seb/seb39_main_026#1]
### Purpose
프로젝트 진행에 앞서 프로젝트 관리 및 알림과 관련된 기능 세팅

### To-Do
- [x]  1. Github - Discord 채널간 웹후크 알림 연동
- [x]  2. Kanban Board 세팅
- [x]  3. Issue-Template 세팅

### Check-List
- [ ]  1. 프로젝트 관리와 관련하여 개선이 필요한 사항이 있는지 확인
- [ ]  2. 이슈 생성시 네이밍 컨벤션에 대해 개선이 필요한 사항이 있는지 확인
