### ISSUE TITLE
[PLAN] 사용자 요구사항 정의서

### ISSUE THREAD

**Issue by devEdok13** [codestates-seb/seb39_main_026#3]
### Purpose
사용자 요구사항 정의서 작성

### To-Do
- [ ]  1. 사용자 요구사항들을 취합하여 정리
- [ ]  2. 사용자 요구사항 정의서 작성

### Check-List
- [ ]  1. 수정사항이 있는지 확인
